{% set name = "asteval" %}
{% set version = "0.9.28" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 91bc7d7826bb9c33f4a5a3ef0a8a50fbd5a4695001944ff1d4e0163c413c0a91

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python

test:
  imports:
    - asteval
  requires:
    - pytest

about:
  home: "http://github.com/newville/asteval"
  license: "OSI Approved :: MIT"
  license_family: MIT
  license_file: LICENSE
  summary: "Safe, minimalistic evaluator of python expression using ast module"
  doc_url: https://newville.github.io/asteval/
  dev_url: https://github.com/newville/asteval

extra:
  recipe-maintainers:
    - https://github.com/gb119
